spring.application.name=eu-job-agent
server.port=8080

# SQLite Configuration (Local Cache)
spring.datasource.url=jdbc:sqlite:job_agent.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LangChain4j Ollama Integration
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen2.5:7b
langchain4j.ollama.chat-model.temperature=0.0
spring.jpa.open-in-view=false

# Disable local Ollama if configured via spring boot starter
langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1
langchain4j.open-ai.chat-model.model-name=llama-3.1-8b-instant
# Read from system environment variable GROQ_API_KEY
#langchain4j.open-ai.chat-model.api-key=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
langchain4j.open-ai.chat-model.api-key=${GROQ_API_KEY}
#langchain4j.open-ai.chat-model.model-name=llama-3.3-70b-versatile
langchain4j.open-ai.chat-model.temperature=0.0